---
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Install dispatcher
        run: pip install -e .[pg_notify]
      - run: pip install pytest
      - run: pytest tests/unit tests/integration

  black:
    name: Run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install black
      - run: black --check dispatcher

  isort:
    name: Run isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install isort
      - run: isort --check dispatcher

  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install mypy
      - run: mypy --ignore-missing-imports dispatcher
