---
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        tests:
          - py_version: '3.10'
            deps: psycopg-binary==3.2.3
          - py_version: '3.11'
            deps: psycopg-binary==3.2.3
          - py_version: '3.13'
            deps: psycopg-binary==3.2.3
          - py_version: '3.13'
            deps: psycopg-binary==3.1.18
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tests.py_version }}

      - name: Install dispatcher
        run: pip install -e .
      - name: Install other dependencies
        run: pip install ${{ matrix.tests.deps }}
      - run: make postgres
      - run: pip install pytest pytest-asyncio

      - run: pytest tests/unit tests/integration -vv -s

  black:
    name: Run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install black
      - run: black --check dispatcher

  isort:
    name: Run isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install isort
      - run: isort --check dispatcher

  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install mypy
      - run: pip install -e .[pg_notify]
      - run: python3 -m pip install types-PyYAML
      - run: mypy --ignore-missing-imports dispatcher

  flake8:
    name: Run flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install flake8
      - run: flake8 dispatcher
