---
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        py_version:
          - '3.10'
          - '3.11'
          - '3.13'
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install dispatcher
        run: pip install -e .[pg_notify]
      - run: make postgres
      - run: pip install pytest pytest-asyncio
      - run: pytest tests/unit tests/integration -vv -s

  black:
    name: Run black
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install black
      - run: black --check dispatcher

  isort:
    name: Run isort
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install isort
      - run: isort --check dispatcher

  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install mypy
      - run: pip install -e .[pg_notify]
      - run: python3 -m pip install types-PyYAML
      - run: mypy --ignore-missing-imports dispatcher

  flake8:
    name: Run flake8
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - run: pip install flake8
      - run: flake8 dispatcher

  benchmark:
    name: Run benchmark tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dispatcher
        run: pip install -e .[pg_notify]
      - run: make postgres
      - run: pip install pytest pytest-benchmark pytest-asyncio
      - run: make benchmark

      - name: Save benchmark results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark_data.json
